### ISSUE TITLE
[Bug]:  Intermittent one-way video on initial accept (TURN-only), both foreground and CallKit background

### ISSUE THREAD

**Issue by 815rx1** [monal-im/Monal#1464]
### What Monal Release channel are you using?

Beta

### iOS system version (if applicable)

18.6.1

### Monal version

6.4.14 (1047)

### Used XMPP server (domain)

kf-media.org

### Which XMPP-Server software are you using?

Prosody

### XMPP Server Software Version

13.0.2 

### How many accounts are you using in Monal?

2

### What happened?

- TURN ICE connects quickly, **audio OK**, but **video is one-way**.
- Waiting **~5–8 s before accepting** increases the chance of **two-way video**.
- **Camera OFF→ON does not fix it**.
- Sent logfiels to info (at) monal (dot) im.

### Anything else?

**Minimal log evidence**
```
# TURN-only & credentials
2025-08-17 21:26:19:486 [MLPipe] RECV: <credentials ... host='turn.example.org' .../>
2025-08-17 21:26:19:681 [MLVoIPProcessor] Initializing webrtc with forceRelay=YES ...

# Jingle with audio+video (senders='both')
2025-08-17 21:51:51:667 [MLPipe] RECV: <jingle ...>
  <content name='1'><description media='video' .../></content>
  <content name='0'><description media='audio' .../></content>
  ... senders='both' ...
</jingle>

# ICE connects (TURN)
2025-08-17 21:51:52:061 [MLCall] New WebRTC ICE state: connected → completed

# Encoder warnings right after accept
2025-08-17 21:51:52:314 [MLStreamRedirect] RTCVideoEncoderH264.mm: frame rate 60 > max allowed 20
2025-08-17 21:51:52:373 [MLStreamRedirect] RTCVideoEncoderH264.mm: frame rate 60 > max allowed 46
```

**Observation**
- Signaling and transport are fine (Jingle, TURN relay).
- Right after accepting, the local video often **does not send** (capture/track not ready when the first SDP is produced), resulting in **one-way video**.
- Happens **both** with foreground accept and CallKit background accept. Waiting before accept improves success.

**Possible suggestions (iOS/WebRTC)**
- Defer `session-accept` / local `setLocalDescription` until **AVCapture/RTCCameraVideoCapturer is running** (first frame/format available).
- Create video transceiver **upfront as `sendrecv`** and **`replaceTrack`** when capture starts.
- If initial local video isn’t sending, **auto-trigger offer/answer (`content-modify`)** once capture becomes active.
- Use conservative **H.264 startup (fps/bitrate)** to avoid immediate encoder throttling.

**Note**
- Same symptom also observed with **Monal (iOS)** ↔ **Conversations/Monocles (Android)**, but this package focuses on **Monal↔Monal**.

### FAQ

- [x] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [x] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [x] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [x] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
> Possible suggestions (iOS/WebRTC)
> 
> a) Defer session-accept / local setLocalDescription until AVCapture/RTCCameraVideoCapturer is running (first frame/format available).

Looks like the best way to fix this.

> b) Create video transceiver upfront as sendrecv and replaceTrack when capture starts.

That could be possible, too, but I think this requires more work than option a.

> c) If initial local video isn’t sending, auto-trigger offer/answer (content-modify) once capture becomes active.

That's even more complicated and needs much work.

> d) Use conservative H.264 startup (fps/bitrate) to avoid immediate encoder throttling.

I'm not sure if this is even possible when using the webrtc lib


**==> I'm happy to take PRs**

**Comment by 815rx1** [comment]
I'm currently in hospital and haven't been able to test the code myself. Sharing the patch in case someone wants to try it.

Patch for testing: Defers session-accept on the callee until the first local video frame is observed (or 2.5s timeout). 
This avoids one-way video when camera capture starts slowly on iOS.

- Audio calls are unaffected (answer immediately).
- OMEMO fingerprint handling is unchanged and still enforced.
- Change is limited to Monal/Classes/MLCall.m.

Please share results/logs; I’ll incorporate feedback when I’m back at a keyboard.

[first-frame-gate.patch](https://github.com/user-attachments/files/21984939/first-frame-gate.patch)

**Comment by tmolitor-stud-tu** [comment]
Some comments:

- Please stick to our coding style documented over here: https://github.com/monal-im/Monal/wiki/coding-style
- Please use the `createTimer()` or `createQueuedTimer()` macros from `HelperTools.h` instead of a hand-rolled one
- Please use the `weakify()` and `strongify()` macros from `MLConstants.h`
- We are currently in the process of switching the license of this project from 2-clause BSD to GPLv3 (or something similar), are you okay with including your contribution under that license, too?

**Comment by 815rx1** [comment]
> Some comments:
> 
> * Please stick to our coding style documented over here: https://github.com/monal-im/Monal/wiki/coding-style
> * Please use the `createTimer()` or `createQueuedTimer()` macros from `HelperTools.h` instead of a hand-rolled one
> * Please use the `weakify()` and `strongify()` macros from `MLConstants.h`
> * We are currently in the process of switching the license of this project from 2-clause BSD to GPLv3 (or something similar), are you okay with including your contribution under that license, too?

Thanks for the guidance!

[first-frame-gate_v2.patch](https://github.com/user-attachments/files/22131363/first-frame-gate_v2.patch)

- I’ve updated the patch to strictly follow the Monal coding style from the wiki (indentation, brace placement, concise comments).
- I replaced the hand-rolled timer with createTimer() from HelperTools.h (no custom GCD timer).
- All blocks now use weakify(self) / strongify(self) from MLConstants.h.
- I kept comments minimal, in line with your style.
- And yes — I’m OK with including my contribution under GPLv3 (or a similar license) as part of your license switch. 

If you spot anything I missed, I’m happy to adjust.

**Comment by tmolitor-stud-tu** [comment]
Still not our coding style and removing comments. Are you using AI?

Also:
```
$ LC_ALL=C git apply --check /tmp/first-frame-gate_v2.patch 
error: corrupt patch at line 27
```

**Comment by lissine0** [comment]
@815rx1 FYI I tested your patch and it didn't fix the issue

**Comment by tmolitor-stud-tu** [comment]
This seems to be AI bullshit, closing the issue.
